services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    platform: linux/amd64  # Forzar arquitectura
    container_name: mi-db-oracle
    environment:
      - ORACLE_PASSWORD=password
      - ORACLE_DISABLE_ASYNCH_IO=true  # Reducir uso de memoria
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "tnsping localhost:1521/XEPDB1 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 120s  # Esperar 2 minutos antes de empezar health checks
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    mem_limit: 2g  # Límite explícito de memoria

  mysql-db:
    image: mysql:8.0
    platform: linux/amd64  # Forzar arquitectura
    container_name: mi-db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --innodb-buffer-pool-size=128M
      - --max-connections=100
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  oracle_data:
    driver: local
  mysql_data:
    driver: local