services:
  app:
    build: .
    container_name: mi-app-universidad
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/tmp/.Xauthority
    networks:
      - app-network
    depends_on:
      oracle-db:
        condition: service_healthy

  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: mi-db-oracle
    environment:
      - ORACLE_PASSWORD=password
    volumes:
      - oracle_data:/opt/oracle/oradata
    ports:
      - "1521:1521"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "tnsping localhost:1521/XEPDB1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  oracle_data: