services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: mi-db-oracle
    environment:
      - ORACLE_PASSWORD=password
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "tnsping localhost:1521/XEPDB1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql-db:
    image: mysql:8.0
    container_name: mi-db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  oracle_data:
  mysql_data: